# Generated by Django 5.1.4 on 2025-01-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fornitore',
            field=models.BooleanField(default=False),
        ),
    ]
