# Generated by Django 5.1.4 on 2025-01-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_product_stock_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornitore',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornitore', to='gymapp.fornitore'),
        ),
    ]
