# Generated by Django 5.1.4 on 2025-01-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_cartorderitem_product_alter_productreview_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
