# Generated by Django 5.1.4 on 2025-01-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_fornitorereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitorereview',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None),
        ),
    ]
