# Generated by Django 5.1.4 on 2025-01-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_alter_fornitorereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categ_type',
            field=models.CharField(choices=[('manubrio', 'Manubrio'), ('panca', 'Panca'), ('bike', 'Bike'), ('bilanciere', 'Bilanciere'), ('collare', 'Collare'), ('disco', 'Disco'), ('lombare', 'Lombare'), ('rack', 'Rack'), ('tapisrulant', 'TapisRulant'), ('unica', 'Unica'), ('vogatore', 'Vogatore'), ('addome', 'Addome')], default='manubrio', max_length=40),
        ),
    ]
