# Generated by Django 5.1.4 on 2025-02-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0013_alter_fornitore_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
